owner: vaishnavvijay-prog
repo: dashverge-status

sites:
  - name: Website
    url: https://dashverge.com
  - name: API
    url: https://dashverge.com/api/access

status-website:
  baseUrl: /dashverge-status
  name: Dashverge
